@startuml
hide circle
skinparam backgroundColor white
skinparam DefaultFontName Arial
skinparam DefaultFontSize 11

skinparam class {
  BackgroundColor white
  BorderColor #888888
  HeaderBackgroundColor #dce8f5
  ArrowColor #000000
  FontColor #000000
  FontSize 11
}

class ResultatAjoutSimplifieDocument

class Fiche {
  statutAttributFiche : Texte [0..*]
}

ResultatAjoutSimplifieDocument "0..1" --> "*" Fiche
@enduml
