@startuml
hide footbox

skinparam sequence {
 arrowColor black
 ParticipantBorderColor RoyalBlue
 ParticipantBackgroundColor white
 LifeLineBorderColor RoyalBlue
 LifeLineBackgroundColor RoyalBlue
 ParticipantFontSize 14
 ParticipantFontName arial
 ParticipantPadding 20
}
skinparam  roundcorner 20


participant "Consommateur\n de documents" as CONS
participant "Gestionnaire de partage\n de documents" as INFRA


CONS-[#black]> INFRA : Flux 7 **DemandeConsultationDocument** [ITI-68] \n <color #FireBrick>HTTP GET[base]/DocumentReference/[id]</color>
activate INFRA
activate CONS
INFRA-[#black]-> CONS : Flux 8 **ResultatDemandeConsultationDocument** [ITI-68] \n <color #FireBrick>HTTP OK 20O (+ document)</color>
deactivate CONS
deactivate INFRA
@enduml